source("imports.R")

tre_sagres <- read.csv("../../data/tre_sagres_unificado.csv", encoding = "UTF-8")
features <- select(tre_sagres, classe, starts_with("nu_"))

information.gain(classe ~ ., features)
gain.ratio(classe ~ ., features)

irregulares <- subset(features, classe == 'IRREGULAR')
nao_irregulares <- subset(features, classe == 'NAO IRREGULAR')

wilcox.test(irregulares$nu_Dispensas, nao_irregulares$nu_Dispensas, paired = F)
wilcox.test(irregulares$nu_Aditivo_Devolucao, nao_irregulares$nu_Aditivo_Devolucao, paired = F)
wilcox.test(irregulares$nu_Aditivo_Devolucao_Prop_Contratos, nao_irregulares$nu_Aditivo_Devolucao_Prop_Contratos, paired = F)
wilcox.test(irregulares$nu_Aditivo_Devolucao_Prop_Eleitores, nao_irregulares$nu_Aditivo_Devolucao_Prop_Eleitores, paired = F)

wilcox.test(irregulares$nu_Aditivo_Prazo, nao_irregulares$nu_Aditivo_Prazo, paired = F)
wilcox.test(irregulares$nu_Aditivo_Valor, nao_irregulares$nu_Aditivo_Valor, paired = F)
wilcox.test(irregulares$nu_Aditivos_Totais, nao_irregulares$nu_Aditivos_Totais, paired = F)
wilcox.test(irregulares$nu_Convites, nao_irregulares$nu_Convites, paired = F)
wilcox.test(irregulares$nu_Dispensas_Prop_Contratos, nao_irregulares$nu_Dispensas_Prop_Contratos, paired = F)
wilcox.test(irregulares$nu_Aditivo_Prazo_Prop_Contratos, nao_irregulares$nu_Aditivo_Prazo_Prop_Contratos, paired = F)
wilcox.test(irregulares$nu_Aditivo_Valor_Prop_Contratos, nao_irregulares$nu_Aditivo_Valor_Prop_Contratos, paired = F)
wilcox.test(irregulares$nu_Aditivos_Totais_Prop_Contratos, nao_irregulares$nu_Aditivos_Totais_Prop_Contratos, paired = F)
wilcox.test(irregulares$nu_Convites_Prop_Contratos, nao_irregulares$nu_Convites_Prop_Contratos, paired = F)
wilcox.test(irregulares$nu_Dispensas_Prop_Eleitores, nao_irregulares$nu_Dispensas_Prop_Eleitores, paired = F)
wilcox.test(irregulares$nu_Aditivo_Prazo_Prop_Eleitores, nao_irregulares$nu_Aditivo_Prazo_Prop_Eleitores, paired = F)
wilcox.test(irregulares$nu_Aditivo_Valor_Prop_Eleitores, nao_irregulares$nu_Aditivo_Valor_Prop_Eleitores, paired = F)
wilcox.test(irregulares$nu_Aditivos_Totais_Prop_Eleitores, nao_irregulares$nu_Aditivos_Totais_Prop_Eleitores, paired = F)
wilcox.test(irregulares$nu_Convites_Prop_Eleitores, nao_irregulares$nu_Convites_Prop_Eleitores, paired = F)
